//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replacement
    {
        public int id_replacement { get; set; }
        public System.DateTime date { get; set; }
        public int id_lesson { get; set; }
        public int id_teacher { get; set; }
        public int id_subject { get; set; }
        public int id_group { get; set; }
        public int id_cabinet { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Сabinet Сabinet { get; set; }
    }
}
